all:
	# g++ triangle.cpp /home/colby/work/cbxGitHubPro/language/c/06.opengl/glad.c  -lglfw3 -lGL -lm -lXrandr -lXi -lX11 -lXxf86vm -lpthread -ldl -lXinerama -lXcursor 
	g++ demo.cpp /home/colby/work/cbxGitHubPro/language/c/06.opengl/glad.c  -lglfw3 -lGL -lm -lXrandr -lXi -lX11 -lXxf86vm -lpthread -ldl -lXinerama -lXcursor 
	./a.out
	rm a.out 